spring:
  application:
    name: businessdonamin-product
  cloud:
    config:
      enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger.html

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"